# Generated by Django 4.2.19 on 2025-02-08 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raj', '0003_store_rajreview_chaicertirajcertificateficate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChaiCertirajCertificateficate',
            new_name='rajCertificate',
        ),
    ]
